#!/usr/bin/env bash
# Run this INSIDE the "supabase" LXC (201): pct exec 201 -- bash /root/setup.sh
#
# Installs Docker, brings up the official self-hosted Supabase stack
# (Postgres + GoTrue auth + PostgREST + Storage + Realtime + Kong + Studio),
# and clones this project's repo (just needed for the supabase/*.sql migrations
# and this deploy/ folder's migrate.sh).
set -euo pipefail

GIT_URL="${GIT_URL:-https://github.com/Konstantine26/airsoft-economy.git}"
APP_DIR="/opt/airsoft-economy"
SUPABASE_DIR="/opt/supabase"
SECRETS_FILE="/root/supabase-secrets.env"

# --- 1. Docker ---------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com | sh
fi

# --- 2. Official self-hosted Supabase docker compose --------------------
if [ ! -d "$SUPABASE_DIR" ]; then
  git clone --depth 1 https://github.com/supabase/supabase.git "$SUPABASE_DIR"
fi
cd "$SUPABASE_DIR/docker"
cp -n .env.example .env

# --- 3. Generate secrets (only once; re-running setup.sh won't rotate them) ---
# JWT generation is inlined (not a sibling script) so this file stays a single
# self-contained unit that works when fetched via `curl | bash`.
b64url() { openssl base64 -e -A | tr '+/' '-_' | tr -d '='; }

gen_jwt() {
  local role="$1" secret="$2"
  local iat exp header payload signing_input signature
  iat=$(date +%s)
  exp=$((iat + 315360000)) # +10 years, matches Supabase's own example tokens
  header=$(printf '{"alg":"HS256","typ":"JWT"}' | b64url)
  payload=$(printf '{"role":"%s","iss":"supabase","iat":%d,"exp":%d}' "$role" "$iat" "$exp" | b64url)
  signing_input="${header}.${payload}"
  signature=$(printf '%s' "$signing_input" | openssl dgst -sha256 -hmac "$secret" -binary | b64url)
  echo "${signing_input}.${signature}"
}

if [ ! -f "$SECRETS_FILE" ]; then
  POSTGRES_PASSWORD=$(openssl rand -hex 24)
  JWT_SECRET=$(openssl rand -hex 32)
  DASHBOARD_USERNAME="admin"
  DASHBOARD_PASSWORD=$(openssl rand -hex 12)

  ANON_KEY=$(gen_jwt anon "$JWT_SECRET")
  SERVICE_ROLE_KEY=$(gen_jwt service_role "$JWT_SECRET")

  cat > "$SECRETS_FILE" <<EOF
# Generated by deploy/supabase/setup.sh on $(date -u +%FT%TZ). Keep this file private.
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
JWT_SECRET=$JWT_SECRET
ANON_KEY=$ANON_KEY
SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
DASHBOARD_USERNAME=$DASHBOARD_USERNAME
DASHBOARD_PASSWORD=$DASHBOARD_PASSWORD
EOF
  chmod 600 "$SECRETS_FILE"
fi
# shellcheck disable=SC1090
source "$SECRETS_FILE"

# --- 4. Patch the compose .env with our secrets + public URLs -----------
# Fill in real values once you've picked a domain (see deploy/cloudflared).
API_DOMAIN="${API_DOMAIN:-api.example.com}"

set_env() {
  local key="$1" value="$2"
  if grep -q "^${key}=" .env; then
    sed -i "s#^${key}=.*#${key}=${value}#" .env
  else
    echo "${key}=${value}" >> .env
  fi
}

set_env POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
set_env JWT_SECRET "$JWT_SECRET"
set_env ANON_KEY "$ANON_KEY"
set_env SERVICE_ROLE_KEY "$SERVICE_ROLE_KEY"
set_env DASHBOARD_USERNAME "$DASHBOARD_USERNAME"
set_env DASHBOARD_PASSWORD "$DASHBOARD_PASSWORD"
set_env SITE_URL "https://${API_DOMAIN}"
set_env API_EXTERNAL_URL "https://${API_DOMAIN}"
set_env SUPABASE_PUBLIC_URL "https://${API_DOMAIN}"

# --- 5. Start the stack ---------------------------------------------------
docker compose pull
docker compose up -d

# --- 6. Clone this project's repo, just for supabase/*.sql + deploy/ ----
if [ ! -d "$APP_DIR" ]; then
  git clone "$GIT_URL" "$APP_DIR"
fi

# --- 7. Run migrations once, then install a timer so future git pushes ---
#        to supabase/*.sql get applied automatically every 5 min.
chmod +x "$APP_DIR/deploy/supabase/migrate.sh"
"$APP_DIR/deploy/supabase/migrate.sh"

cp "$APP_DIR/deploy/supabase/airsoft-migrate.service" /etc/systemd/system/
cp "$APP_DIR/deploy/supabase/airsoft-migrate.timer" /etc/systemd/system/
systemctl daemon-reload
systemctl enable --now airsoft-migrate.timer

# --- 8. `update` command for manual on-demand updates -----------------
install -m 755 "$APP_DIR/deploy/supabase/update-cli.sh" /usr/local/bin/update

echo
echo "=== Supabase is up. Credentials saved to $SECRETS_FILE ==="
echo "ANON_KEY (put this in the app's EXPO_PUBLIC_SUPABASE_ANON_KEY):"
grep ANON_KEY= "$SECRETS_FILE"
echo
echo "Studio (admin UI) is on port 3000 - keep it LAN/VPN-only, do not expose via the tunnel."
echo "Migrations applied and auto-update timer installed (every 5 min)."
echo "Type 'update' inside this container any time to force an OS + Docker image + migration refresh."
